# Generated by Django 5.0.6 on 2024-05-21 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_Post',
            new_name='BlogPost',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(help_text='Please write your comment'),
        ),
    ]
