# Generated by Django 5.0.6 on 2024-05-21 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(help_text='Please write your comment')),
                ('blog_post', models.ForeignKey(help_text='Please write blog for which comment is there', on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
                ('comment_by', models.ForeignKey(help_text='Please write the commenter name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['comment_date'],
            },
        ),
    ]
