# Generated by Django 5.0.6 on 2024-06-09 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['post_date', 'blogger_name'], 'verbose_name': 'Blog_Post', 'verbose_name_plural': 'Blog_Posts'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_date', 'comment_by'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogger_photo', models.ImageField(upload_to='images/')),
                ('name', models.OneToOneField(help_text='Name of the blogger', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blogger',
                'verbose_name_plural': 'Bloggers',
            },
        ),
    ]
