# Generated by Django 5.0.6 on 2024-06-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_options_alter_comment_options_blogger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogger',
            options={'ordering': ['name'], 'verbose_name': 'Blogger', 'verbose_name_plural': 'Bloggers'},
        ),
        migrations.AddField(
            model_name='blogger',
            name='phone',
            field=models.CharField(blank=True, help_text='Mobile number', max_length=10, null=True),
        ),
    ]
