# Generated by Django 5.0.6 on 2024-06-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogger_options_blogger_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='blogger_photo',
            field=models.ImageField(help_text='Profile Picture', upload_to='images/'),
        ),
    ]
