# Generated by Django 5.0.6 on 2024-06-09 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogger_blogger_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blogger_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogger'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_by',
            field=models.ForeignKey(help_text='Please write the commenter name', on_delete=django.db.models.deletion.CASCADE, to='blog.blogger'),
        ),
    ]
